<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Hemanths-MacBook-Air.local" failures="1" tests="4" name="Test" time="35.094" errors="0" timestamp="2024-02-22T13:08:35 EST">
  <testcase classname="MyAtomation.SeleniumAutomation.Tests.TestngTests2" name="test3" time="0.004"/>
  <testcase classname="MyAtomation.SeleniumAutomation.Tests.TestngTests1" name="test1" time="17.781"/>
  <testcase classname="MyAtomation.SeleniumAutomation.Tests.TestngTests1" name="test2" time="0.594">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="MyAtomation.SeleniumAutomation.Tests.TestngTests1" name="test2" time="0.53">
    <failure type="java.lang.AssertionError" message="expected [Incorrect email or passwor.] but found [Incorrect email or password.]">
      <![CDATA[java.lang.AssertionError: expected [Incorrect email or passwor.] but found [Incorrect email or password.]
at MyAtomation.SeleniumAutomation.Tests.TestngTests1.test2(TestngTests1.java:84)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test -->
